// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEChTpRx6Z_c6B_ahFXSDXCVtMLaTU68A',
    appId: '1:503771997517:web:d1269d3718251a7d380304',
    messagingSenderId: '503771997517',
    projectId: 'heart-to-heart-e3cc1',
    authDomain: 'heart-to-heart-e3cc1.firebaseapp.com',
    storageBucket: 'heart-to-heart-e3cc1.firebasestorage.app',
    measurementId: 'G-T76VG5KKTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy6-xC15fXcwoh74UWB7S5B4ux0ciRq1M',
    appId: '1:503771997517:android:f9730e74be8b7dd4380304',
    messagingSenderId: '503771997517',
    projectId: 'heart-to-heart-e3cc1',
    storageBucket: 'heart-to-heart-e3cc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYnIsx_LO6UoGdipyJL2EC81tUuPyKFdY',
    appId: '1:503771997517:ios:163ea506539ad46a380304',
    messagingSenderId: '503771997517',
    projectId: 'heart-to-heart-e3cc1',
    storageBucket: 'heart-to-heart-e3cc1.firebasestorage.app',
    iosClientId: '503771997517-gc28c5qje0cf4cjunkhl8r6n594hjvdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.h2h',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYnIsx_LO6UoGdipyJL2EC81tUuPyKFdY',
    appId: '1:503771997517:ios:163ea506539ad46a380304',
    messagingSenderId: '503771997517',
    projectId: 'heart-to-heart-e3cc1',
    storageBucket: 'heart-to-heart-e3cc1.firebasestorage.app',
    iosClientId: '503771997517-gc28c5qje0cf4cjunkhl8r6n594hjvdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.h2h',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEChTpRx6Z_c6B_ahFXSDXCVtMLaTU68A',
    appId: '1:503771997517:web:fb128a473aea9bfc380304',
    messagingSenderId: '503771997517',
    projectId: 'heart-to-heart-e3cc1',
    authDomain: 'heart-to-heart-e3cc1.firebaseapp.com',
    storageBucket: 'heart-to-heart-e3cc1.firebasestorage.app',
    measurementId: 'G-2SLFRFY3FC',
  );
}
